In [1]:
# !pip install tensorflow-gpu

In [2]:
# !pip install tensorflow

In [1]:
import tensorflow as tf
print(tf.__version__)

2.17.0


In [2]:
import sys
sys.version

'3.11.7 | packaged by Anaconda, Inc. | (main, Dec 15 2023, 18:05:47) [MSC v.1916 64 bit (AMD64)]'

In [3]:
from tensorflow.keras.preprocessing.text import one_hot

In [6]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [4]:
# sent=["The world is a better place",
#       "Marvel series is my favourite movie",
#       "I like DC movies",
#       "the cat is eating the food",
#       "Tom and Jerry is my favourite movie",
#       "Python is my favourite programming language"
#       ]

In [5]:
sent

['The world is a better place',
 'Marvel series is my favourite movie',
 'I like DC movies',
 'the cat is eating the food',
 'Tom and Jerry is my favourite movie',
 'Python is my favourite programming language']

In [6]:
# EXPLAINATION
# OHE
# POST PADDING PRE PADDING
# OHE VALUES ---> VECTORS

In [7]:
# vocabulary_size is number of unique words
# whenver we have own dataset we use this Embedding Layer in Keras

### Word embedding Techniques using Embedding Layer in Keras

In [8]:
# Vocabulary size initalization
voc_size = 500

### ONE HOT REPRESENTATION

In [9]:
onehot_repr = [one_hot(words, voc_size) for words in sent] 

In [10]:
onehot_repr # not will be same every time it have random in it

[[417, 466, 296, 33, 175, 15],
 [162, 249, 296, 180, 47, 216],
 [455, 341, 490, 346],
 [417, 381, 296, 13, 417, 390],
 [354, 202, 94, 296, 180, 47, 216],
 [49, 296, 180, 47, 342, 295]]

### WORD EMBEDDING REPRESENTAION   

In [11]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
import numpy as np

In [12]:
# Lets consider one Maximum Sentence Length
sent_length = 8
embedded_docs = pad_sequences(onehot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[  0   0 417 466 296  33 175  15]
 [  0   0 162 249 296 180  47 216]
 [  0   0   0   0 455 341 490 346]
 [  0   0 417 381 296  13 417 390]
 [  0 354 202  94 296 180  47 216]
 [  0   0  49 296 180  47 342 295]]


In [13]:
dim=10

In [14]:
model = Sequential()
model.add(Embedding(input_dim=voc_size, output_dim=dim))
model.compile('adam', 'mse')

In [18]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ embedding (Embedding)                │ (8, 10)                     │           5,000 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 5,000 (19.53 KB)

 Trainable params: 5,000 (19.53 KB)

 Non-trainable params: 0 (0.00 B)

In [16]:
model.predict(embedded_docs[0])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 189ms/step


array([[ 0.04285867,  0.00925612,  0.01598505, -0.01058301,  0.03027937,
         0.02582505,  0.04273916, -0.03642325,  0.02733247,  0.01260656],
       [ 0.04285867,  0.00925612,  0.01598505, -0.01058301,  0.03027937,
         0.02582505,  0.04273916, -0.03642325,  0.02733247,  0.01260656],
       [ 0.00425667,  0.02762396, -0.00969989, -0.0348698 , -0.00783216,
        -0.04112983, -0.00830963,  0.00749739, -0.0098892 ,  0.03736261],
       [-0.04328538, -0.01554513, -0.03302746,  0.00966571,  0.04175602,
         0.00644735,  0.04347763, -0.03880932, -0.03097094,  0.04848111],
       [ 0.02840691, -0.04481025, -0.00501569,  0.02738574, -0.01628323,
         0.03070983, -0.00152204, -0.04114615, -0.04591835, -0.04860867],
       [ 0.00157609, -0.04037306,  0.00600576,  0.03933607, -0.00360916,
         0.03250777,  0.01070497,  0.02455137,  0.00990443, -0.03859419],
       [ 0.03983149, -0.02495962,  0.02413727, -0.03548385, -0.00381137,
        -0.04466876,  0.01777891, -0.00750484

In [17]:
model.predict(embedded_docs[1])

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step


array([[ 0.04285867,  0.00925612,  0.01598505, -0.01058301,  0.03027937,
         0.02582505,  0.04273916, -0.03642325,  0.02733247,  0.01260656],
       [ 0.04285867,  0.00925612,  0.01598505, -0.01058301,  0.03027937,
         0.02582505,  0.04273916, -0.03642325,  0.02733247,  0.01260656],
       [-0.03384376,  0.04458382, -0.00177169,  0.01744387, -0.00302179,
         0.01257623,  0.04152847,  0.0113103 , -0.0117344 ,  0.02845714],
       [ 0.04513801, -0.03031981,  0.04564871, -0.0415571 , -0.02654739,
         0.04366568,  0.02891612,  0.02747469,  0.00842751,  0.01486189],
       [ 0.02840691, -0.04481025, -0.00501569,  0.02738574, -0.01628323,
         0.03070983, -0.00152204, -0.04114615, -0.04591835, -0.04860867],
       [ 0.03697034, -0.02048377, -0.03751479,  0.02140107, -0.0460794 ,
        -0.02802284,  0.00866877, -0.03148234,  0.0421576 ,  0.04284965],
       [-0.02651519, -0.01984692,  0.02246623, -0.01401882, -0.01847253,
         0.04600798,  0.01337272, -0.03909208

In [21]:
# print(model.predict(embedded_docs))

In [ ]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]